/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cusc.certificategenerationsystem.view;

import com.cusc.certificategenerationsystem.db.DatabaseProcess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author PC_HP
 */
public class CertificateOfStudent extends javax.swing.JPanel {

    /**
     * Creates new form TamPanel
     */
    public CertificateOfStudent() {
        initComponents();
        displayCertificate();
        
    }
    private void displayCertificate(){
        try {
            String certificateID = CertificatesJPanel.cetID;
            String sql = "SELECT * FROM [Certificate] cer \n" +
                "JOIN Registry R ON R.CourseID=cer.CourseID AND R.StudentID=cer.StudentID\n" +
                "JOIN Students S ON S.StudentID=cer.StudentID\n" +
                "JOIN Course C ON C.CourseID=cer.CourseID\n" +
                "JOIN Grades G ON cer.GradeID=G.GradeID\n" +
                "JOIN ClassList CL ON CL.StudentID=cer.StudentID\n" +
                "JOIN Class CLS ON CLS.ClassID=CL.ClassID AND CLS.CourseID=C.CourseID " +
                    "WHERE CertificateID='"+certificateID+"'";
            ResultSet rs = DatabaseProcess.displayInformation(sql);
            if(rs.next()){
                lbCertificateName.setText(rs.getString("CertificateName"));
                lbName.setText(rs.getString("Name"));
                lbCourse.setText(rs.getString("CourseName"));
                lbClass.setText(rs.getString("ClassName"));
                lbGrade.setText(rs.getString("GradeName"));
                lbDOB.setText(rs.getString("DOB"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CertificateOfStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbCourse = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        lbAward = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbDOB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbGrade = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbCertificateName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(2000, 3000));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 60)); // NOI18N
        jLabel12.setText("The principal signed it");

        lbName.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        lbName.setText("[Name]");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        jLabel1.setText("Full Name:");

        lbCourse.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        lbCourse.setText("[Course]");

        lbClass.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        lbClass.setText("[Class]");

        lbAward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cusc/certificategenerationsystem/images/icon_award.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 100)); // NOI18N
        jLabel2.setText("CERTIFICATE ");

        lbDOB.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        lbDOB.setText("[DOB]");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        jLabel6.setText("Course:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        jLabel9.setText("Grade:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        jLabel10.setText("Class:");

        lbGrade.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        lbGrade.setText("[Grade]");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        jLabel4.setText("Date of birth:");

        lbCertificateName.setFont(new java.awt.Font("Times New Roman", 0, 90)); // NOI18N
        lbCertificateName.setText("APTECH A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbCertificateName, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addComponent(lbAward)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76)
                        .addComponent(lbCertificateName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAward)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbName))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbDOB))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbCourse))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbGrade))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbClass))
                .addGap(140, 140, 140)
                .addComponent(jLabel12)
                .addGap(1193, 1193, 1193))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbAward;
    private javax.swing.JLabel lbCertificateName;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbCourse;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbGrade;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
