package com.cusc.certificategenerationsystem.studentview;

import com.cusc.certificategenerationsystem.view.LoginJFrame;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author PC_HP
 */
public class StudentJFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentJFrame
     */
    public StudentJFrame() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2); 
        switchScreen(new StudentProfileJPanel());
        setColor(pnlProfileMenu,indProfile);
        this.setIconImage(new ImageIcon(getClass().getResource("/com/cusc/certificategenerationsystem/images/icon_logo.png")).getImage());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrayMenu = new javax.swing.JPanel();
        pnlProfileMenu = new javax.swing.JPanel();
        lbProfile = new javax.swing.JLabel();
        indProfile = new javax.swing.JPanel();
        pnlLogOutMenu = new javax.swing.JPanel();
        lbLogOut = new javax.swing.JLabel();
        indLogOut = new javax.swing.JPanel();
        pnlView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Information Form");
        setPreferredSize(new java.awt.Dimension(1900, 1000));

        pnlGrayMenu.setBackground(new java.awt.Color(23, 35, 51));
        pnlGrayMenu.setPreferredSize(new java.awt.Dimension(333, 968));

        pnlProfileMenu.setBackground(new java.awt.Color(23, 35, 51));
        pnlProfileMenu.setPreferredSize(new java.awt.Dimension(120, 88));
        pnlProfileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlProfileMenuMousePressed(evt);
            }
        });

        lbProfile.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbProfile.setForeground(new java.awt.Color(255, 255, 255));
        lbProfile.setText("Profile");

        indProfile.setBackground(new java.awt.Color(23, 35, 51));
        indProfile.setPreferredSize(new java.awt.Dimension(4, 0));

        javax.swing.GroupLayout indProfileLayout = new javax.swing.GroupLayout(indProfile);
        indProfile.setLayout(indProfileLayout);
        indProfileLayout.setHorizontalGroup(
            indProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        indProfileLayout.setVerticalGroup(
            indProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlProfileMenuLayout = new javax.swing.GroupLayout(pnlProfileMenu);
        pnlProfileMenu.setLayout(pnlProfileMenuLayout);
        pnlProfileMenuLayout.setHorizontalGroup(
            pnlProfileMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileMenuLayout.createSequentialGroup()
                .addComponent(indProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbProfile)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlProfileMenuLayout.setVerticalGroup(
            pnlProfileMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbProfile)
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(indProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        pnlLogOutMenu.setBackground(new java.awt.Color(23, 35, 51));
        pnlLogOutMenu.setPreferredSize(new java.awt.Dimension(120, 88));
        pnlLogOutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLogOutMenuMousePressed(evt);
            }
        });

        lbLogOut.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lbLogOut.setText("Log out");

        indLogOut.setBackground(new java.awt.Color(23, 35, 51));
        indLogOut.setPreferredSize(new java.awt.Dimension(4, 0));

        javax.swing.GroupLayout indLogOutLayout = new javax.swing.GroupLayout(indLogOut);
        indLogOut.setLayout(indLogOutLayout);
        indLogOutLayout.setHorizontalGroup(
            indLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        indLogOutLayout.setVerticalGroup(
            indLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlLogOutMenuLayout = new javax.swing.GroupLayout(pnlLogOutMenu);
        pnlLogOutMenu.setLayout(pnlLogOutMenuLayout);
        pnlLogOutMenuLayout.setHorizontalGroup(
            pnlLogOutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutMenuLayout.createSequentialGroup()
                .addComponent(indLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbLogOut)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        pnlLogOutMenuLayout.setVerticalGroup(
            pnlLogOutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbLogOut)
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(indLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlGrayMenuLayout = new javax.swing.GroupLayout(pnlGrayMenu);
        pnlGrayMenu.setLayout(pnlGrayMenuLayout);
        pnlGrayMenuLayout.setHorizontalGroup(
            pnlGrayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProfileMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addComponent(pnlLogOutMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        pnlGrayMenuLayout.setVerticalGroup(
            pnlGrayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrayMenuLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(pnlProfileMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pnlLogOutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );

        pnlView.setPreferredSize(new java.awt.Dimension(1500, 800));
        pnlView.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGrayMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGrayMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
            .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlProfileMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProfileMenuMousePressed
        setColor(pnlProfileMenu,indProfile);
        resetColor(new JPanel[]{pnlLogOutMenu}, new JPanel[]{indLogOut});
        switchScreen(new StudentProfileJPanel());
    }//GEN-LAST:event_pnlProfileMenuMousePressed

    private void pnlLogOutMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogOutMenuMousePressed
        setColor(pnlLogOutMenu,indLogOut);
        resetColor(new JPanel[]{pnlProfileMenu}, new JPanel[]{indProfile});
        JFrame frame = new LoginJFrame();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlLogOutMenuMousePressed
    private void setColor(JPanel pane, JPanel ind){
        pane.setBackground(new Color(41,57,80));
        ind.setBackground(new Color(240,240,240));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators){
        for(int i=0;i< pane.length;i++){
            pane[i].setBackground(new Color(23,35,51));
        } 
        
        for(int j=0;j< indicators.length;j++){
            indicators[j].setBackground(new Color(23,35,51));
        }
    }
    private void switchScreen(JPanel pane){
        JPanel pnlSwitch = pane;
        pnlView.removeAll();
        pnlView.add(pane);
        pnlView.validate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel indLogOut;
    private javax.swing.JPanel indProfile;
    private javax.swing.JLabel lbLogOut;
    private javax.swing.JLabel lbProfile;
    private javax.swing.JPanel pnlGrayMenu;
    private javax.swing.JPanel pnlLogOutMenu;
    private javax.swing.JPanel pnlProfileMenu;
    private javax.swing.JPanel pnlView;
    // End of variables declaration//GEN-END:variables
}
