package com.cusc.certificategenerationsystem.studentview;

import com.cusc.certificategenerationsystem.db.DatabaseConnection;
import com.cusc.certificategenerationsystem.db.DatabaseProcess;
import com.cusc.certificategenerationsystem.view.HomeJPanel;
import com.cusc.certificategenerationsystem.view.LoginJFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC_HP
 */
public class StudentProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form pnlProfile
     */
    public StudentProfileJPanel() {
        initComponents();
        HomeJPanel.setColorCombobox(new JComboBox[]{cbbClassID,cbbCourseID});
        showResultForm();
        displayCourse();
        displayClass();
        showPayments();
        DatabaseProcess.tableModel = new DefaultTableModel();
        DatabaseProcess.loadData("SELECT E.[SubjectID],[SubjectName],[Mark] "
                + "FROM [dbo].[Exam] E JOIN [dbo].[Subjects] SUB "
                + "ON SUB.SubjectID=E.SubjectID WHERE E.StudentID='"+txtStudentID.getText()+"'", tblMark);
    }
        private void showResultForm(){
        try {
            String user = LoginJFrame.username;
            String sql= "SELECT * FROM Students WHERE Username='"+user+"'";
            ResultSet rs = DatabaseProcess.displayInformation(sql);
            while(rs.next()){
                txtStudentID.setText(rs.getString("StudentID"));
                txtName.setText(rs.getString("Name"));
                dcDOB.setDate(rs.getDate("DOB"));
                String gender=rs.getString("Gender");
                if(gender == "Male"){
                    radMale.setSelected(true);
                    radFemale.setSelected(false);
                }
                if(gender == "Female"){
                    radFemale.setSelected(true);
                    radMale.setSelected(false);
                }
                txtUsername.setText(rs.getString("Username"));
                txaAddress.setText(rs.getString("Address"));
                txtPhone.setText(rs.getString("Phone"));
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Load Result form FAILED! Please try again!","Message", 1);
        }
    }

    private void displayCourse(){
        cbbCourseID.removeAllItems();
        DatabaseProcess.loadDataCombobox("SELECT * FROM Course C " +
            "JOIN [dbo].[Registry] R ON R.CourseID=C.CourseID " +
            "JOIN [dbo].[Students] S on S.StudentID=R.StudentID " +
            "WHERE Username='"+LoginJFrame.username+"'", this.cbbCourseID, "CourseID");
        String query = "SELECT * FROM Course WHERE CourseID = ?";
        DatabaseProcess.loadDataTextfield(query, this.cbbCourseID, this.txtCourseName, "CourseName");
    }
    private void showPayments(){
        try {
            String course = cbbCourseID.getSelectedItem().toString();
            String sql = "SELECT * FROM Registry " +
                "WHERE CourseID='"+course+"' AND StudentID='"+txtStudentID.getText()+"'";
            ResultSet rs = DatabaseProcess.displayInformation(sql);
            if(rs.next()){
                txtPayments.setText(rs.getString("Payments"));
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex.getMessage(),"Message", JOptionPane.YES_NO_OPTION);
        }
    }
    private void displayClass(){
        cbbClassID.removeAllItems();
        String sql = "SELECT S.[StudentID],[Name],[DOB],[Gender],\n" +
            "[Address],[Phone],[Username],[Status],R.[CourseID],[RegisDate],\n" +
            "[Payments],C.[ClassID]  FROM Students S\n" +
            "JOIN ClassList cl ON cl.StudentID=S.StudentID\n" +
            "JOIN Class c ON c.ClassID=cl.ClassID\n" +
            "JOIN Registry r ON S.StudentID=r.StudentID and c.CourseID=r.CourseID \n" +
            "WHERE r.CourseID='"+cbbCourseID.getSelectedItem().toString()+"' AND r.StudentID='"+txtStudentID.getText()+"'";
        DatabaseProcess.loadDataCombobox(sql, cbbClassID, "ClassID");
        DatabaseProcess.loadDataTextfield("SELECT * FROM Class WHERE ClassID = ?", cbbClassID, txtClassName, "ClassName");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGroupGender = new javax.swing.ButtonGroup();
        txtStudentID = new javax.swing.JTextField();
        radFemale = new javax.swing.JRadioButton();
        dcDOB = new com.toedter.calendar.JDateChooser();
        cbbCourseID = new javax.swing.JComboBox();
        txtUsername = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        lbCourse = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        lbDOB = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        scpAddress = new javax.swing.JScrollPane();
        txaAddress = new javax.swing.JTextArea();
        radMale = new javax.swing.JRadioButton();
        lbStudentID = new javax.swing.JLabel();
        pnlProfile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbCourseName = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lbClass = new javax.swing.JLabel();
        lbClassName = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        pnlMark = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMark = new javax.swing.JTable();
        lbPayments = new javax.swing.JLabel();
        txtPayments = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();
        cbbClassID = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        txtStudentID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtStudentID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtStudentID.setEnabled(false);

        radFemale.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGender.add(radFemale);
        radFemale.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radFemale.setText("Female");
        radFemale.setEnabled(false);

        dcDOB.setBackground(new java.awt.Color(255, 255, 255));
        dcDOB.setDateFormatString("yyyy-MM-dd");
        dcDOB.setEnabled(false);
        dcDOB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cbbCourseID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbbCourseID.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbbCourseIDPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txtUsername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUsername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUsername.setEnabled(false);

        lbUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbUsername.setText("Username:");

        lbCourse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbCourse.setText("CourseID:");

        lbGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbGender.setText("Gender:");

        lbPhone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbPhone.setText("Phone:");

        lbDOB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbDOB.setText("Date of Birth:");

        lbAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbAddress.setText("Address:");

        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPhone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPhone.setEnabled(false);

        txaAddress.setColumns(20);
        txaAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txaAddress.setRows(5);
        txaAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txaAddress.setEnabled(false);
        scpAddress.setViewportView(txaAddress);

        radMale.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGender.add(radMale);
        radMale.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radMale.setSelected(true);
        radMale.setText("Male");
        radMale.setEnabled(false);

        lbStudentID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbStudentID.setText("StudentID:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Profile");

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        lbName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbName.setText("Full Name:");

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtName.setEnabled(false);

        lbCourseName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbCourseName.setText("CourseName:");

        txtCourseName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCourseName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCourseName.setEnabled(false);

        lbClass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbClass.setText("ClassID:");

        lbClassName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbClassName.setText("ClassName:");

        txtClassName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtClassName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtClassName.setEnabled(false);

        pnlMark.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMark.setLayout(new java.awt.BorderLayout());

        tblMark.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblMark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMark.setEnabled(false);
        tblMark.setRowHeight(20);
        tblMark.setRowMargin(5);
        jScrollPane1.setViewportView(tblMark);

        pnlMark.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lbPayments.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbPayments.setText("Payments:");

        txtPayments.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPayments.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPayments.setEnabled(false);

        btnChangePassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        cbbClassID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbbClassID.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbClass)
                    .addComponent(lbCourseName)
                    .addComponent(lbCourse)
                    .addComponent(lbPhone)
                    .addComponent(lbAddress)
                    .addComponent(lbUsername)
                    .addComponent(lbGender)
                    .addComponent(lbDOB)
                    .addComponent(lbStudentID)
                    .addComponent(lbName)
                    .addComponent(lbClassName)
                    .addComponent(lbPayments))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dcDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                        .addComponent(txtStudentID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(radMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(scpAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbCourseID, 0, 508, Short.MAX_VALUE)
                        .addComponent(txtPhone))
                    .addComponent(txtPayments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassword)
                    .addComponent(cbbClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(pnlMark, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbClassID, cbbCourseID, scpAddress, txtClassName, txtCourseName, txtPayments, txtPhone, txtStudentID, txtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudentID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStudentID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDOB, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radMale)
                            .addComponent(radFemale)
                            .addComponent(lbGender))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUsername))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAddress))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbPhone))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCourse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbCourseID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCourseName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbClass)
                            .addComponent(cbbClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbClassName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtClassName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPayments, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPayments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(btnChangePassword)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcDOB, txtName, txtStudentID});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbClassID, cbbCourseID, txtClassName, txtCourseName, txtPayments});

    }// </editor-fold>//GEN-END:initComponents

    private void cbbCourseIDPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbbCourseIDPopupMenuWillBecomeInvisible
        String query = "SELECT * FROM Course WHERE CourseID = ?";
        DatabaseProcess.loadDataTextfield(query, this.cbbCourseID, this.txtCourseName, "CourseName");
        displayClass();
        showPayments();
        DatabaseProcess.tableModel = new DefaultTableModel();
        DatabaseProcess.loadData("SELECT E.[SubjectID],[SubjectName],[Mark] "
                + "FROM [dbo].[Exam] E JOIN [dbo].[Subjects] SUB "
                + "ON SUB.SubjectID=E.SubjectID WHERE E.StudentID='"+txtStudentID.getText()+"'", tblMark);
    }//GEN-LAST:event_cbbCourseIDPopupMenuWillBecomeInvisible

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        JFrame frame = new ChangePasswordJFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JComboBox cbbClassID;
    private javax.swing.JComboBox cbbCourseID;
    private com.toedter.calendar.JDateChooser dcDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbClassName;
    private javax.swing.JLabel lbCourse;
    private javax.swing.JLabel lbCourseName;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPayments;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbStudentID;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel pnlMark;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JScrollPane scpAddress;
    private javax.swing.JTable tblMark;
    private javax.swing.JTextArea txaAddress;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPayments;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
